### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by Hartii14** [pedroo21/AntiBotAttack#1]
This plugin is working well, disallow bots to join a server, but even i cant join its says error at login:

how could i fix this?

@pedroo21

**Comment by plourenco** [comment]
Can you post a screenshot of the error?

When the plugin is preventing an attack, it disallows all OFFLINE players (with cracked versions) from entering the server. If you want to prevent this, you can enable the `protection.ping.enabled = true` in config.
